#!/bin/sh

case $# in
2) A=$1 B=$2;;
*) echo "usage: "`basename $0`" OLD NEW"; exit 2 ;;
esac

# e -c -F '((fullscreen . maximized))' -e '(ediff-files "'"$A"'" "'"$B"'")'
e -c -F '((width . 180)(height . 48))' -e '(ediff-files "'"$A"'" "'"$B"'")'
