#!/bin/bash

target=$HOME/share/info/DIR
rm -f "$target"

nullglob=$(shopt -p nullglob)
shopt -s nullglob

fmt.path "$INFOPATH" |
while read d; do
    echo processing ${d}
    for info in "${d}"/*.info; do
	install-info "${info}" ${target}
    done
done
eval $nullglob

# vim: set filetype=sh :
