#!/bin/bash

# target=$HOME/share/info/DIR
targetdir="/c/Program Files (x86)/Emacs/emacs-24.3/info"
target="${targetdir}/DIR"
rm -f "$target"

nullglob=$(shopt -p nullglob)
shopt -s nullglob

fmt.path "$INFOPATH" |
while read d; do
    echo processing ${d}
    for info in "${d}"/*.info*; do
        [ "${d}" = "$targetdir" ] || install -m 644 "$info" "$targetdir"
	install-info "${info}" "${target}"
    done
done
eval $nullglob

# vim: set filetype=sh :
