#!/bin/bash
tagsfile=./tags

usage() {
    echo "usage: $(basename $0)"
    echo " builds ./tags, from the combined contents of the default include path."
}

case $# in 
0)      ;;
*)      usage; exit 1;;
esac

rm -f $tagsfile
gccpath |
while read d; do
    echo "Tagging $d..."
    time -p ctags $CTAGSFLAGS -aR "$d"
done
ls -lh $tagsfile
