#!/bin/bash
tagsfiles="\
  ./tags\
  ./TAGS\
"

usage() {
    echo "usage: $(basename $0)"
    echo " builds ./tags or ./TAGS, from the combined contents of the default include path."
    echo " set CTAGSFLAGS=-e if you want Emacs TAGS."
}

case $# in 
0)      ;;
*)      usage; exit 1;;
esac

rm -f $tagsfiles
gccpath |
while read d; do
    echo "Tagging $d..."
    time -p ctags $CTAGSFLAGS -aR "$d"
done
ls -lh $tagsfiles
