#!/bin/sh
TMPDIR=${TMPDIR:-/tmp}
# PATH=/usr/bin:/bin

xterm=rxvt
geometry=${xGEOMETRY:-80x40}
pager=${PAGER:-less}
temporary=${TMPDIR}/x.tmp.$$
rm=/bin/rm
who=${LOGNAME:-${USER:-me}}
where=`/bin/uname -n`
cmd=${1:-${SHELL:-/bin/sh}}
name=`basename $cmd`

printf "%s" "$* " > ${temporary}
printf "%s" "2>&1 | ${pager}" >> ${temporary}
chmod +x ${temporary}

case $# in 
0)	title="$who@$where $name"		;;
1)	title="@$where  $name"			;;
2)	title="@$where  $name $2"		;;
3)	title="@$where  $name $2 $3"		;;
4)	title="@$where  $name $2 $3 $4"		;;
5)	title="@$where  $name $2 $3 $4 $5"	;;
*)	title="@$where  $name $2 $3 $4 $5 ..."	;;
esac

# fn=$(whichXFont font)
# fb=$(whichXFont boldFont)
fn=9x15
fb=9x15b

(${xterm} -fn "$fn" -fb "$fb" \
    -fg gray75 -bg gray10 \
    -geometry ${geometry} +sb -n "$title" -T "$title" -e ${temporary} &&
 ${rm} -f ${temporary}) &

# end of xo
